batch_size: &batch_size 128
num_epochs: 50
n_freeze: all

dataloader:
  train:
    TinyImagenetFastDataLoader: # TinyImagenetDataLoader
      batch_size: *batch_size
      train: true
  test:
    TinyImagenetFastDataLoader: # TinyImagenetDataLoader
      batch_size: *batch_size
      train: false

init_fn:
  xavier_uniform_:
    gain: !eval sqrt(2)  # ReLU gain: sqrt(2)
loss:
  CrossEntropyLoss: { }
optim:
  Adam:
    betas: !!python/tuple
      - 0.9
      - 0.95
    lr: !eval 1e-3 * batch_size / 128
scheduler:
  SequentialLR:
    schedulers:
      - LinearLR:
          total_iters: !eval num_epochs // 20
      - CosineAnnealingLR:
          T_max: !eval num_epochs - num_epochs // 20
    milestones:
      - !eval num_epochs // 20